fail if SHIELD store/policy/schedule missing

diff --git a/jobs/cf-containers-shield-link/templates/bin/ctl b/jobs/cf-containers-shield-link/templates/bin/ctl
--- a/jobs/cf-containers-shield-link/templates/bin/ctl
+++ b/jobs/cf-containers-shield-link/templates/bin/ctl
@@ -25,10 +25,40 @@ case $1 in
       unless api_key   = p('shield-daemon.provisioning_key', nil)
         api_key = link("shield-daemon").p("auth.api_keys").values.first
       end
-      schedule  = p('backups.schedule')
-      retention = p('backups.retention-policy')
-      store     = p('backups.store')
+      schedule = p('backups.schedule.name')
+      policy   = p('backups.retention-policy.name')
+      store    = p('backups.store.name')
     -%>
+    SHIELD_CONFIG=$(mktemp --tmpdir auto.XXXXXX)
+    trap "rm -rf ${SHIELD_CONFIG}" INT TERM QUIT EXIT
+
+    export SHIELD_API_TOKEN=<%= api_key %>
+    export SHIELD_SKIP_SSL_VERIFY=true
+
+    # Create a specific  config file for shield-agent stuff, to avoid race
+    # conditions in case we are colocated with shield-daemon.
+    shield -c ${SHIELD_CONFIG} create-backend default <%= daemon_url %>
+
+    store_uuid=$(   shield stores    --raw | jq -r ".[] | select(.name == \"<%= store %>\")| .uuid // \"\"")
+    schedule_uuid=$(shield schedules --raw | jq -r ".[] | select(.name == \"<%= schedule %>\")| .uuid // \"\"")
+    policy_uuid=$(  shield policies  --raw | jq -r ".[] | select(.name == \"<%= policy %>\")| .uuid // \"\"")
+    errors=no
+    if [[ "${store_uuid:-X}" == "X" ]]; then
+      echo "ERROR: requested SHIELD store '<%= store %>' does not exist."
+      errors=yes
+    fi
+    if [[ "${schedule_uuid:-X}" == "X" ]]; then
+      echo "ERROR: requested SHIELD store '<%= schedule %>' does not exist."
+      errors=yes
+    fi
+    if [[ "${policy_uuid:-X}" == "X" ]]; then
+      echo "ERROR: requested SHIELD store '<%= policy %>' does not exist."
+      errors=yes
+    fi
+    if [[ "${errors}" == "yes" ]]; then
+      exit 1
+    fi
+
     mkdir -p /var/vcap/store/cf-containers-broker/envdir
     cd /var/vcap/store/cf-containers-broker/envdir
     echo "<%= daemon_url %>"  > SHIELD_ENDPOINT
@@ -36,7 +66,9 @@ case $1 in
     echo "<%= api_key %>"     > SHIELD_API_TOKEN
     echo "true"               > SHIELD_SKIP_SSL_VERIFY
     echo "<%= schedule %>"    > SHIELD_BACKUPS_SCHEDULE
-    echo "<%= retention %>"   > SHIELD_BACKUPS_RETENTION
+    echo "<%= policy %>"      > SHIELD_BACKUPS_RETENTION
+    echo "<%= policy %>"      > SHIELD_BACKUPS_RETENTION_POLICY
+    echo "<%= policy %>"      > SHIELD_BACKUPS_POLICY
     echo "<%= store %>"       > SHIELD_BACKUPS_STORE
 
     echo "<%= spec.address %>" > DOCKER_HOST_IP
